In [2]:
import torch
from torch.nn import RNN, LSTM, Transformer

In [18]:
rnn = RNN(3,2,2)
rnn.state_dict()

OrderedDict([('weight_ih_l0',
              tensor([[ 0.3160, -0.6480, -0.1247],
                      [-0.1216, -0.6594, -0.1895]])),
             ('weight_hh_l0',
              tensor([[-0.1899,  0.1208],
                      [ 0.1284,  0.3731]])),
             ('bias_ih_l0', tensor([-0.1650, -0.6067])),
             ('bias_hh_l0', tensor([ 0.5002, -0.1214])),
             ('weight_ih_l1',
              tensor([[-0.2978, -0.0279],
                      [ 0.3297, -0.2358]])),
             ('weight_hh_l1',
              tensor([[-0.1719, -0.0727],
                      [-0.4386,  0.2370]])),
             ('bias_ih_l1', tensor([0.6436, 0.0275])),
             ('bias_hh_l1', tensor([ 0.6449, -0.2606]))])